steps:
  # Step 0: Auth Databricks
  - id: databricks-auth
    name: ghcr.io/databricks/cli:latest
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Authenticating with Databricks..."
        databricks auth login --profile databricks-gcp-account

  # Step 1: Initialize Terraform
  - id: terraform-init
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Initializing Terraform..."
        terraform init -upgrade

# Step 2: Auth GCP
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'gcp-auth'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        set -euo pipefail
        echo "Verifying GCP authentication..."
        gcloud auth list --filter=status:ACTIVE --format="value(account)"
        gcloud config list project --format="value(core.project)"

  # Step 3: Validate the Terraform configuration
  - id: terraform-validate
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Validating Terraform configuration..."
        terraform validate

  # Step 4: Generate Terraform plan and save it to a file
  - id: terraform-plan
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Running Terraform plan..."
        terraform plan  -input=false -compact-warnings -out=tfplan.out

  # Step 5: Apply the saved plan automatically
  - id: terraform-apply
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Applying Terraform plan..."
        terraform apply -input=false -auto-approve tfplan.out
