options:
      logging: CLOUD_LOGGING_ONLY
steps:
    # 1) Terraform as you already have it
  - name: hashicorp/terraform:1.6.6
    id: terraform-apply
    env:
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com
    entrypoint: sh
    args:
      - -lc
      - |
        export TF_LOG=DEBUG
        terraform init
        terraform plan -out=tfplan
        terraform state rm databricks_mws_workspaces.this
        terraform apply -auto-approve