steps:
  - id: terraform init
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args: ["-lc", "terraform init -upgrade"]

  - id: terraform validate
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args: ["-lc", "terraform validate"]

  - id: terraform plan
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args: ["-lc", "terraform plan -input=false -compact-warnings"]