steps:
  # Step 1: Set up Terraform
  - id: 'terraform-setup'
  - name: 'hashicorp/terraform:1.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Setting up Terraform..."
        terraform version

  # Step 2: Authenticate with GCP (automatic in Cloud Build)
  - id: 'gcp-auth'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        set -euo pipefail
        echo "Verifying GCP authentication..."
        gcloud auth list --filter=status:ACTIVE --format="value(account)"
        gcloud config list project --format="value(core.project)"

  # Step 3: Initialize Terraform
  - id: 'terraform-init'
  - name: 'hashicorp/terraform:1.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd /workspace
        echo "Initializing Terraform..."
        terraform init
        terraform validate

  # Step 4: Create Terraform plan
  - id: 'terraform-plan'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        set -euo pipefail
        cd /workspace

        # Install Terraform & tools
        apt-get update && apt-get install -y unzip wget jq
        wget -q https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
        unzip -q terraform_1.5.0_linux_amd64.zip
        mv terraform /usr/local/bin/
        chmod +x /usr/local/bin/terraform

        # GCP SA impersonation (for any GCP ops)
        gcloud config set auth/impersonate_service_account andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com

        # Databricks Accounts OAuth (authoritative)
        export DATABRICKS_HOST="https://accounts.gcp.databricks.com"
        export DATABRICKS_ACCOUNT_ID="e11e38c5-a449-47b9-b37f-0fa36c821612" # gitleaks:allow
        export DATABRICKS_CLIENT_ID="9e52f02e-3246-4b6b-aca2-de6b7b849f4d"  # gitleaks:allow
        export DATABRICKS_CLIENT_SECRET="dose88c6c1b3f2571d5c97314c8a7313bf78" # gitleaks:allow

        # Sanity-check for hidden characters
        printf 'ID   bytes: '; printf '%s' "$$DATABRICKS_CLIENT_ID" | wc -c
        printf 'SECRET bytes: '; printf '%s' "$$DATABRICKS_CLIENT_SECRET" | wc -c
        printf '%s' "$$DATABRICKS_CLIENT_SECRET" | xxd -p  # should show only printable bytes, no 0a at end

        # Test A: no scope
        curl -sS -X POST "https://accounts.gcp.databricks.com/oidc/accounts/$${DATABRICKS_ACCOUNT_ID}/v1/token" \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          --data "grant_type=client_credentials&client_id=$$DATABRICKS_CLIENT_ID&client_secret=$$DATABRICKS_CLIENT_SECRET" | jq .

        # Test B: with scope (Databricks commonly uses this)
        curl -sS -X POST "https://accounts.gcp.databricks.com/oidc/accounts/$${DATABRICKS_ACCOUNT_ID}/v1/token" \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          --data "grant_type=client_credentials&client_id=$$DATABRICKS_CLIENT_ID&client_secret=$$DATABRICKS_CLIENT_SECRET&scope=all-apis" | jq .

        # Debug
        export TF_LOG=DEBUG
        export DATABRICKS_DEBUG_TRUNCATE_BYTES=10000

        echo "Pre-flight token test..."
        TOKEN_JSON="$(curl -sS -X POST "https://accounts.gcp.databricks.com/oidc/accounts/$${DATABRICKS_ACCOUNT_ID}/v1/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "grant_type=client_credentials" \
          --data-urlencode "client_id=$${DATABRICKS_CLIENT_ID}" \
          --data-urlencode "client_secret=$${DATABRICKS_CLIENT_SECRET}" \
          --data-urlencode "scope=all-apis")"

        if echo "$$TOKEN_JSON" | jq -e '.access_token' >/dev/null 2>&1; then
          echo "Token OK (redacted)"; echo "$$TOKEN_JSON" | jq 'del(.access_token)'
        else
          echo "ERROR: OAuth failed. Response:"
          echo "$$TOKEN_JSON"
          exit 1
        fi

        echo "Creating Terraform plan..."
        terraform plan -out=tfplan

  # Step 5: Apply Terraform (conditional on plan success)
  - id: 'terraform-apply'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        set -euo pipefail
        cd /workspace

        # Install Terraform & tools
        apt-get update && apt-get install -y unzip wget jq
        wget -q https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
        unzip -q terraform_1.5.0_linux_amd64.zip
        mv terraform /usr/local/bin/
        chmod +x /usr/local/bin/terraform

        # GCP SA impersonation (for any GCP ops)
        gcloud config set auth/impersonate_service_account andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com

        # Databricks Accounts OAuth (authoritative)
        export DATABRICKS_HOST="https://accounts.gcp.databricks.com"
        export DATABRICKS_ACCOUNT_ID="e11e38c5-a449-47b9-b37f-0fa36c821612" # gitleaks:allow
        export DATABRICKS_CLIENT_ID="9e52f02e-3246-4b6b-aca2-de6b7b849f4d"  # gitleaks:allow
        export DATABRICKS_CLIENT_SECRET="dose88c6c1b3f2571d5c97314c8a7313bf78" # gitleaks:allow

        # Optional: re-check token before apply
        TOKEN_JSON="$(curl -sS -X POST "https://accounts.gcp.databricks.com/oidc/accounts/$${DATABRICKS_ACCOUNT_ID}/v1/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "grant_type=client_credentials" \
          --data-urlencode "client_id=$${DATABRICKS_CLIENT_ID}" \
          --data-urlencode "client_secret=$${DATABRICKS_CLIENT_SECRET}" \
          --data-urlencode "scope=all-apis")"
        if ! echo "$$TOKEN_JSON" | jq -e '.access_token' >/dev/null 2>&1; then
          echo "ERROR: OAuth failed. Response:"
          echo "$$TOKEN_JSON"
          exit 1
        fi

        echo "Applying Terraform configuration..."
        terraform apply -auto-approve tfplan

        echo "Terraform apply completed successfully!"

        echo "Databricks Workspace URL:"
        terraform output databricks_host
