options:
      logging: CLOUD_LOGGING_ONLY

steps:
  - id: whoami
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        curl -s -H "Metadata-Flavor: Google" \
          http://metadata/computeMetadata/v1/instance/service-accounts/default/email
        echo
        gcloud auth list
        echo "Sample identity token (truncated):"
        gcloud auth print-identity-token | cut -c1-40
        
  # 1) terraform init
  - id: terraform-init
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Initializing Terraform configuration..."
        export TF_LOG=DEBUG
        terraform init -upgrade

  # 2) terraform plan
  - id: terraform-plan
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
         echo "Planning Terraform configuration..."
         export TF_LOG=DEBUG
         terraform plan -input=false -compact-warnings -out=tfplan.out

  # 3) terraform apply test
  - id: terraform-apply
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Applying Terraform configuration..."
        export TF_LOG=DEBUG
        terraform apply -input=false -auto-approve tfplan.out
