substitutions:
  _TARGET_SA: andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com
  _TF_VERSION: "1.6.6"

steps:
  # Install terraform once
  - id: terraform-init 
    name: hashicorp/terraform:1.6.6 
    entrypoint: sh 
    args: 
      - -lc 
      - | 
        echo "Initializing Terraform..." 
        terraform init -upgrade

  # terraform plan
  - id: terraform-plan
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud config set auth/impersonate_service_account ${_TARGET_SA}
        export GOOGLE_OAUTH_ACCESS_TOKEN="$(gcloud auth print-access-token)"
        terraform plan -input=false -compact-warnings -out=tfplan.out

  # terraform apply
  - id: terraform-apply
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud config set auth/impersonate_service_account ${_TARGET_SA}
        export GOOGLE_OAUTH_ACCESS_TOKEN="$(gcloud auth print-access-token)"
        export TF_LOG=INFO
        terraform apply -input=false -auto-approve tfplan.out
