options:
      logging: CLOUD_LOGGING_ONLY

steps:
  # 1) terraform init
  - id: terraform-init
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Initializing Terraform configuration..."
        export TF_LOG=DEBUG
        terraform init -upgrade

  # 2) terraform plan
  - id: terraform-plan
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
         echo "Planning Terraform configuration..."
         export TF_LOG=DEBUG
         terraform plan -input=false -compact-warnings -out=tfplan.out

  # 3) terraform apply
  - id: terraform-apply
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        echo "Applying Terraform configuration..."
        export TF_LOG=DEBUG
        terraform apply -input=false -auto-approve tfplan.out
