options:
      logging: CLOUD_LOGGING_ONLY
steps:
  - id: terraform-init
    name: hashicorp/terraform:1.6.6
    env:
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com
    entrypoint: sh
    args:
      - -lc
      - |
        export TF_LOG=DEBUG
        terraform init

  - id: terraform-plan
    name: hashicorp/terraform:1.6.6
    env:
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com
    entrypoint: sh
    args:
      - -lc
      - |
        export TF_LOG=DEBUG
        terraform plan -out=tfplan

  - id: terraform-apply
    name: hashicorp/terraform:1.6.6
    env:
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com
    entrypoint: sh
    args:
      - -lc
      - |
        export TF_LOG=DEBUG
        terraform state rm databricks_mws_workspaces.this
        terraform apply -auto-approve