substitutions:
  _TARGET_SA: andrea-tardif-sa@fe-dev-sandbox.iam.gserviceaccount.com

steps:
  # 1) Mint a token and save it for later steps
  - id: mint-token
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud config set auth/impersonate_service_account ${_TARGET_SA}
        ACCESS_TOKEN="$(gcloud auth print-access-token)"
        printf '%s' "$ACCESS_TOKEN" > /workspace/google_access_token.txt

  # 2) Terraform init/plan/apply in the hashicorp image, reading the token file
  - id: terraform-init
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        export GOOGLE_OAUTH_ACCESS_TOKEN="$(cat /workspace/google_access_token.txt)"
        terraform init -upgrade

  - id: terraform-plan
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        export GOOGLE_OAUTH_ACCESS_TOKEN="$(cat /workspace/google_access_token.txt)"
        terraform plan -input=false -compact-warnings -out=tfplan.out

  - id: terraform-apply
    name: hashicorp/terraform:1.6.6
    entrypoint: sh
    args:
      - -lc
      - |
        export GOOGLE_OAUTH_ACCESS_TOKEN="$(cat /workspace/google_access_token.txt)"
        export TF_LOG=INFO
        terraform apply -input=false -auto-approve tfplan.out
